spring:
  application:
    name: order_management

  profiles:
    active: dev

  datasource:
    url: jdbc:h2:mem:order_management;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

---
spring:
  config:
    activate:
      on-profile: postgres

  datasource:
    url: jdbc:postgresql://localhost:5432/order_management
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: validate
